### ISSUE TITLE
TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by stu0440** [ultralytics/JSON2YOLO#106]
Annotations /root/autodl-tmp/datasets/coco/annotations/instancesonly_filtered_train.json:   4%|███▏                                                                              | 714/18732 [00:02<01:09, 257.80it/s]
Traceback (most recent call last):
  File "general_json2yolo.py", line 396, in <module>
    convert_coco_json(
  File "general_json2yolo.py", line 315, in convert_coco_json
    file.write(("%g " * len(line)).rstrip() % line + "\n")
TypeError: must be real number, not NoneType

**Comment by UltralyticsAssistant** [comment]
👋 Hello @stu0440, thank you for submitting a `ultralytics/JSON2YOLO` 🚀 issue! 

To help us address your concern efficiently, please provide the following information:

1. For bug reports:
   - A clear and concise description of the bug 🐛
   - A minimum reproducible example (MRE) that demonstrates the issue
   - Your environment details (OS, Python version, package versions)
   - Expected behavior vs. actual behavior
   - Any error messages or logs related to the issue – you've already included some of this, thank you!

Make sure to check if your issue has already been reported in existing issues to avoid duplicates.

🏷️ If you need to add more information, please comment on this issue. An Ultralytics engineer will assist you soon.

Thank you for contributing to the improvement of our project!

**Comment by huizhenlai** [comment]
I meet the same problem.

**Comment by pderrenger** [comment]
@huizhenlai thank you for sharing your solution. If the issue persists, please ensure you're using the latest version of the package. If you have further questions, feel free to ask.

**Comment by glenn-jocher** [comment]
Thanks @stu0440. This class-mapping edge case is fixed on main now in commit ff25841 by skipping COCO91 categories that do not map to COCO80 instead of writing None as a class id. Please update from main or use ultralytics.data.converter.convert_coco() in the main Ultralytics package.
