### ISSUE TITLE
 KeyError: 'iscrowd'

### ISSUE THREAD

**Issue by Mary14-design** [ultralytics/JSON2YOLO#83]
I am trying to convert `instances_train2017.json` from [https://cocodataset.org/#home](url) and it returns the following error 

`Traceback (most recent call last):
  File "/tmp/workspace/codes/JSON2YOLO/general_json2yolo.py", line 393, in <module>
    convert_coco_json(
  File "/tmp/workspace/codes/JSON2YOLO/general_json2yolo.py", line 286, in convert_coco_json
    box = np.array(ann["bbox"], dtype=np.float64)
KeyError: 'bbox'`

Any idea on how to solve this error?

**Comment by glenn-jocher** [comment]
Thanks @Mary14-design. This is fixed on main now in commit ff25841 by treating missing iscrowd as False instead of indexing the key directly. I verified the converter path after the change.
